#########################[ Solary-Economy ]#########################
##                                                                ##
##                 Encontrou algum bug? Reporte!                  ##
##                                                                ##
##                Email: theprog.matheus@gmail.com                ##
##                     Discord: sr_edition                        ##
##                                                                ##
####################################################################



#/------------------------------------------------------------------/
#     Autor: ${project.author}
#     Versão: ${project.version}
#/------------------------------------------------------------------/



# Versão do arquivo de configuração. Não altere.
config-version: 1.0

# =====================[ IDIOMA DAS MENSAGENS ]===================== #
lang:
  # Idioma padrão utilizado nas mensagens do plugin.
  # Exemplo: "en_us", "pt_br"
  default: "pt_br"

  # Se verdadeiro, o plugin usará o idioma individual do jogador
  # (baseado nas configurações de idioma do Minecraft).
  # OBS: Nem sempre isso funcionará corretamente.
  individual: true

# =====================[ CONFIGURAÇÕES DO BANCO DE DADOS ]===================== #
database:
  # Tipo de banco de dados a ser utilizado.
  # Opções: "sqlite", "mysql", "mariadb"
  type: "sqlite"

  # Configurações do MySQL/MariaDB (se o tipo for "mysql" ou "mariadb").
  # Ignorado se o tipo for "sqlite".
  mysql:
    host: "localhost"
    port: 3306
    database: "solaryeconomy"
    username: "root"
    password: "senha"
    table-prefix: "seco_"